ci: remove test from workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -7,34 +7,18 @@ on:
         description: 'New version tag (e.g., 1.0.0)'
         required: true
 jobs:
-  validate_version:
-    runs-on: ubuntu-22.04
-    
-    steps:
-    - name: Validate input version
-      run: |
-        version="${{ github.event.inputs.version }}"
-        if [[ ! $version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(-([a-zA-Z0-9_-]+))?$ ]]; then
-          echo "Error: Version must have the format 'x.y.z' or 'x.y.z-<string>', where x, y, and z are numbers."
-          exit 1
-        fi
-
-  check: 
-    runs-on: ubuntu-22.04
-    
-    steps:  
-    - name: Checkout repository
-      uses: actions/checkout@v3
-
-    - name: Test
-      uses: devcontainers/ci@v0.3
-      with:
-        runCmd: zsh test.sh
-  
   publish:
     runs-on: ubuntu-22.04
     
     steps:
+      - name: Validate input version
+        run: |
+          version="${{ github.event.inputs.version }}"
+          if [[ ! $version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(-([a-zA-Z0-9_-]+))?$ ]]; then
+            echo "Error: Version must have the format 'x.y.z' or 'x.y.z-<string>', where x, y, and z are numbers."
+            exit 1
+          fi
+
       - name: Checkout repository
         uses: actions/checkout@v3
 
