ci: some more tag checks

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -23,8 +23,22 @@ jobs:
     - name: Validate input version
       run: |
         version="${{ github.event.inputs.version }}"
-        if [[ ! $version =~ ^[0-9] ]]; then
-          echo "Error: Version must start with a number."
+        if [[ ! $version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([a-zA-Z0-9]+))?$ ]]; then
+          echo "Error: Version must have the format 'x.y.z' or 'x.y.z-<string>', where x, y, and z are numbers."
+          exit 1
+        fi
+
+    - name: Check if tag already exists and compare with the latest tag
+      run: |
+        git fetch --tags
+        if git rev-parse ${{ github.event.inputs.version }} >/dev/null 2>&1; then
+          echo "Error: Tag already exists."
+          exit 1
+        fi
+
+        latest_tag=$(git tag --list --sort=-version:refname | grep -P "^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$" | head -n 1)
+        if [ ! -z "$latest_tag" ] && [[ $latest_tag > ${{ github.event.inputs.version }} ]]; then
+          echo "Error: The new tag version must be greater than the last tag on the remote."
           exit 1
         fi
 
